sudo: false
language: node_js
cache:
  directories:
    - tests/elm-stuff
    - sysconfcpus
node_js:
  - "4.7"
install:
  - npm install -g elm@0.18.0 elm-test
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-test

